nytlabs/st-core

- server/connection.go
> tiny typo caused panic

- core/library.go
- core/logic.go
> adding and,or,not

- server/block.go
- server/connection.go
- server/group.go
- server/helpers.go
- server/link.go
- server/server_test.go
- server/source.go
a little helper function for getting the ID from a request; a couple of little tests
> test + helper

- core/block.go
- core/block_test.go
- core/types.go
- server/block.go
- server/group.go
- server/router.go
- server/server_test.go
put value routes back in the mix, but no paths. fixed all the tests.
> returning of value routes (1/2)

- server/block.go
- server/connection.go
- server/group.go
- server/link.go
- server/router.go
- server/server.go
- server/server_test.go
- server/source.go
- server/update.go
- server/websocket.go
__THIS IS PR 2/2__ please look at #54 first!
> Api Cleaning (2/2)

- core/priorityqueue.go
- core/sources_test.go
> added priority output to pqPeek and pqPop

- server/group.go
- static/js/component/app.js
- static/js/component/autocomplete.js
- static/js/model/block.js
- static/js/model/link.js
- static/js/model/model.js
- static/js/model/source.js
minimal working sources in UI. 
- lists sources in the drop down
- allows creation of sources
- allows grouping of sources
- allows linking
> Sources UI

- server/group.go
- server/source.go
sources didn't import/export properly. now they do.
> fixing source import/export

- core/types.go
- server/group.go
- server/monitor.go
- server/server.go
- server/server_test.go
- server/update.go
- static/css/main.css
- static/index.html
- static/js/component/app.js
- static/js/component/block.js
- static/js/component/clipboard.js
- static/js/model/model.js
This PR adds support for copy and pasting.
Notes:
- when pasting a pattern, it will paste directly over the selected pattern you have copied. staggered pastes won't be included until we sort out the massive over-rendering mess caused by crank.
- crank updates are included in this release. oops. cranks are now batched.
> copy & paste

- core/interface_NSQ.go
- core/server.go
- core/types.go
- server/link.go
- server/server_test.go
- server/source.go
- static/js/component/panel.js
- static/js/component/panellist.js
- static/js/model/model.js
This allows you to enter source parameters in the UI
> Sourceparams

- server/group.go
fixing error on source import.
> fixing source import issue

- static/js/component/block.js
making it so the little crank thing doesn't spend 2 beats on position 7
> fixing off-by-one

- core/block.go
I calculated the number of messages incorrectly with the previous PR. This PR stops the panic when using a latch. the issue was that we were counting connections on a pin w/o a message as a possible delivery. with a latch, only 1 message is delivered over one of two pins, meaning that any connection on the pin w/o a message was also counted as a possible delivery as well.
> fixing the blocking broadcast fix

- core/assertions.go
- core/random.go
... mostly just because I got my laptop up and running with go
> super simple bug bears

- core/core_blocks.go
- core/object.go
again, super simple. Just tidying.
> moved keys to a new file concerning objects

- core/random.go
just cleaning up branches ready to get back into the swing of thigns
> uniform random number now pushes

- main.go
- server/server.go
- server/server_test.go
This doesn't really do anything, but removes a little bit of labour for when we do need something specific.
> Settings file

- core/library.go
- core/random.go
> Exponential

- static/css/main.css
- static/js/component/grouptree.js
> fix for tree view (#133)

- docs/append.md
- docs/delay.md
- docs/endpoint.md
- docs/exponential.md
- docs/flush.md
- docs/gate.md
- docs/get.md
- docs/head.md
- docs/identity.md
- docs/init.md
- docs/iserror.md
- docs/keys.md
- docs/last.md
- docs/latch.md
- docs/len.md
- docs/log.md
- docs/merge.md
- docs/plus.md
- docs/poisson.md
- docs/set.md
- docs/sink.md
- docs/tail.md
- docs/template.md
- docs/timestamp.md
This is a super simple approach to documentation. One file per block. Simple, clear descriptions with supporting examples as gists and links to wikipedia for maths or more complex stuff. 
to come:
* md files for everything
* a static site generator to turn md files into html for github pages
process:
* copy template.md to blockname.md
* edit blockname.md
* commit and push
> Documentation

- core/server.go
> added a new dependency for turning structs to maps

- core/library.go
- core/monads.go
> floor block

- static/js/component/panel.js
- static/js/store/actions.js
- static/js/store/nodes.js
> adding labels/types/names

- static/js/component/panel.js
- static/js/event/router.js
- static/js/store/actions.js
- static/js/store/nodes.js
> adding source panels

- static/js/component/panel.js
> blur text boxes in panel

- static/js/component/app.js
- static/js/component/canvasgraph.js
> double click opens group

- static/css/main.css
- static/js/component/grouptree.js
- static/js/store/nodes.js
> group tree

- static/js/store/selected.js
> source fix

- core/library.go
- core/source_priority_queue.go
> adding pqclear

- static/js/component/app.js
- static/js/component/autocomplete.js
- static/js/component/canvasgraph.js
> blocks now appear where you create them.

- static/css/main.css
- static/js/component/app.js
- static/js/component/autocomplete.js
- static/js/component/canvasgraph.js
> 0,0 in center of screen

- static/js/store/nodes.js
> centering grouping/ungrouping on 0,0/relative to group

- server/group.go
> unmarshal hidden route ledger

- static/js/store/nodes.js
> removing autohide

- core/block_test.go
- core/library.go
- core/networkIO.go
this got wiped when I closed the shit websocket pull request
> Http request

- core/array_blocks.go
- core/library.go
- core/membership.go
- core/networkIO.go
- core/source_websocket.go
- core/sources.go
- core/types.go
- core/websocket_test.go
- server/connection.go
- server/group.go
this also contains the edits from #210 which should be merged first, and should be considered a req for this. 
this is a websocket source, with connect, receive, and send blocks.
> websocket source

- core/core_blocks.go
- core/library.go
- core/sources.go
- core/types.go
- server/library.go
- static/js/store/library.js
also removes Pusher entirely and removes the server + endpoint from the library.
> suggestion for categorising blocks

- .gitignore
- core/interface_stdin.go
- core/library.go
- core/sources.go
- core/types.go
- main.go
- static/js/event/router.js
> first crack at stdin
